### ISSUE TITLE
Wi-Fi Framework Test Case be used to test other AP

### ISSUE THREAD

**Issue by Dejavu610** [domienschepers/wifi-framing#1]
Dear Author，
  Besides freeBSD, can I use the Wi-Fi Framework Test Case be used to test other AP such as routers?

**Comment by domienschepers** [comment]
Yes, you can run the test case against any access point. As mentioned in the troubleshooting section, make sure to verify which IP addresses are used and configure the test case accordingly.

**Comment by Dejavu610** [comment]
Thanks for your reply. Another question I have is whether this tool can implement other attacks the paper mentioned, such as 4.2Queueing of Wi-Fi FTM Requests and 4.3 Queueing of 4-Way Handshake Messages
